apiVersion: v1
kind: Pod
metadata:
  name: "post-install-hook"
  annotations:
    "helm.sh/hook": post-install
spec:
  restartPolicy: Never
  containers:
    - name: "sleep-10"
      image: busybox
      command: [ 'sleep' ]
      args: [ '10' ]