apiVersion: v1
kind: Pod
metadata:
  name: "pre-install-hook"
  annotations:
    "helm.sh/hook": pre-install
spec:
  restartPolicy: Never
  containers:
    - name: "sleep-5"
      image: busybox
      command: [ 'sleep' ]
      args: [ '5' ]