global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'app-python'
    static_configs:
      - targets: [ 'app-python:8080' ]
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'grafana'
    static_configs:
      - targets: [ 'grafana:3000' ]