- name: Install `pip`
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install Docker
  import_tasks: install_docker.yaml

- name: Install Docker Compose
  import_tasks: install_compose.yaml